# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - postgres

  centos:
    image: centos:latest
    command: /bin/bash -c "sed -i -e 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* && sed -i -e 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && yum update -y && yum install -y python3 && yum clean all && pip3 install --upgrade pip && pip install pandas && pip install psycopg2-binary && pip install PyYaml && cd app/ && python3 dim_company_load.py && python3 dim_person_load.py && python3 dim_department_load.py && python3 fact_employees_load.py"
    environment:
      - HOST_DB=db
      - PORT_DB=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=example
    volumes:
      - ./app/:/app/
    networks:
      - postgres

  python_app:
    image: python:3.10.0
    command: /bin/bash -c "pip install flask && pip install psycopg2-binary && cd api/ && flask --app get_employees run --host=0.0.0.0"
    volumes:
      - ./api/:/api/
    environment:
      - FLASK_APP=get_employees.py
      - HOST_DB=db
      - PORT_DB=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=example
    ports:
      - 8088:5000
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
